### PR TITLE
PR for #3: Run additional regression on years 1960+

### LINKED ISSUE #3: Run additional regression on years >= 1960
For [Practice Task 1: Basic Functionality](https://github.com/gentzkow/lab-manual-archive/wiki/Practice-Task):
- Modify the code in analysis/code/analyze_data.py to run an additional regression only on the subset of years greater or equal to 1960.
- Export the model coefficient, standard errors and p-value into a new table output
- Add new table to paper

### PR DESCRIPTION
**Pull request by linxicindyzeng**
Closes #3 

Changes made:
- Edit [analyze_data.py](https://github.com/linxicindyzeng/template_archive/blob/b4e0a33924e33a56335489dbf6fdc47e6d49c41c/analysis/code/analyze_data.py) to run an additional regression on years $\ge$ 1960
- Make subsequent changes throughout the repository to produce two tables with model coefficients, standard errors and p-values of regressions on
     1. the full sample of all years
     2. a subsample of years $\ge$ 1960

Deliverables:
- Updated [paper](https://github.com/linxicindyzeng/template_archive/blob/b4e0a33924e33a56335489dbf6fdc47e6d49c41c/paper_slides/output/paper.pdf)

Draftable Difference:
- See [here](https://draftable.com/compare/MaIAuspbbYaH)

@ShiqiYang2022 Thanks for reviewing this!

### CODE REVIEW

**Review by ShiqiYang2022 — CHANGES_REQUESTED** [review]
Thanks @linxicindyzeng!

I have general comments same as https://github.com/linxicindyzeng/template_archive/pull/2#pullrequestreview-2272772414. Could you please make the revise accordingly? 

You've opened two issues (#1 #3) simultaneously, instead of having issues opened sequentially. In this case, I would suggest you do the following after make the changes I requested:

* First squash-merge #2 to `master` after @ShiqiYang2022 approved.
* Merge `master` into this branch `3-run-additional-regression-on-years-1960+`, and [resolve any conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github).
* Re-run the repo from beginning to end, and post a draftable diff against new `master` branch.
* Tag @ShiqiYang2022 to review the changes again.

Thanks for all of your work!

**Comment by linxicindyzeng** [comment]
@ShiqiYang2022 Thanks a lot! I've revised the current [PR for #3](https://github.com/linxicindyzeng/template_archive/pull/4) according to your general comments in [PR for #1](https://github.com/linxicindyzeng/template_archive/pull/2).

**Comment by ShiqiYang2022** [comment]
@linxicindyzeng Great! Since #2 has been approved, you can feel free to execute the remaining steps in https://github.com/linxicindyzeng/template_archive/pull/4#pullrequestreview-2272886332, and tag me after all these has been done.

**Comment by linxicindyzeng** [comment]
I have merged `master` into branch `3-run-additional-regression-on-years-1960+`, resolved all conflicts, and re-run the repo from beginning to end.

Here are the new [draftable differences](https://draftable.com/compare/escTOHinlnbZ).

@ShiqiYang2022

**Review by ShiqiYang2022 — CHANGES_REQUESTED** [review]
Thanks @linxicindyzeng!

I think my only comment is just there are some accidentally committed files in the `/paper_slides/code` directory. It would be great if you can remove them.

**Comment by linxicindyzeng** [comment]
@ShiqiYang2022 Just deleted them. This is the second time it has happened. Do you know how to avoid committing unnecessary files in the future?

**Comment by ShiqiYang2022** [comment]
@linxicindyzeng Thanks! I think use [`git diff`](https://git-scm.com/docs/git-diff) from command line would help.

**Review by ShiqiYang2022 — APPROVED** [review]
@linxicindyzeng Thanks again for your great work here!

All looks good from my side hence I am approving. Feel free to squash merge back to `master`.

**Comment by linxicindyzeng** [comment]
> @linxicindyzeng Thanks! I think use [`git diff`](https://git-scm.com/docs/git-diff) from command line would help.

Is my understanding correct that we use `git diff` to check and delete unnecessary files every time before we do a final commit? @ShiqiYang2022

**Comment by ShiqiYang2022** [comment]
@linxicindyzeng You can use git diff, I think `git status` can also help. Also, I think if you have set up github integration from your VSCode / have installed github desktop, you can easily check what files you've committed in their interface.

**Comment by linxicindyzeng** [comment]
> @linxicindyzeng You can use git diff, I think `git status` can also help. Also, I think if you have set up github integration from your VSCode / have installed github desktop, you can easily check what files you've committed in their interface.

I see. Thank you so much for the advice!

**Pull request merged**
